package com.sizonenko.bicycleapp.command;

public enum CommandType {
    LOG_IN, LOG_OUT, LANGUAGE, REGISTER, FILL_MAIN, FILL_CALENDAR, FILL_RESERVATION, EDIT_PROFILE, CONFIRM, FILL_CASHIER, FIND_NOT_FINISHED_TRANSACTION, COMPLETE_TRANSACTION, FIND_RESERVATION, RESERVATION
}
